Extend models to accommodate dynamic mentor applications
sef-global/scholarx pull request #140
Opened 2021-05-05 14:13 UTC by Gravewalker666

## Purpose

The purpose of this PR is to fix #139 

## Goals

* To extend models to accommodate dynamic mentor applications

## Approach

* Introduced two new models, 
  * Question
  * MentorResponses
* Removed attributes `application` and `prerequisites` from `mentor` with the related service methods and controllers 
* Added four new endpoints and update one existing to be compatible with the above new models
  * Add Questions
  * Get Questions
  * Apply as a mentor (Updated)
  * Get mentor responses
  * Edit Mentor Responses

More Info : [SEF Hive: ScholarX Model Update to Improve the Mentor Application](https://sef.discourse.group/t/scholarx-model-update-to-improve-the-mentor-application/259?u=gravewalker)

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Test environment
- Postman
- Java Oracle 8
- Apache Maven 3.6.3
- macOS Big Sur

## Learning
- https://www.baeldung.com/jpa-many-to-many
- https://stackoverflow.com/questions/46740624/org-springframework-orm-jpa-jpasystemexception-could-not-set-field-value-post
- https://stackoverflow.com/questions/3585034/how-to-map-a-composite-key-with-jpa-and-hibernate

2021-05-05 16:08 UTC, Piumal1999 requested changes
Good job @Gravewalker666 
Added some comments.

2021-05-05 16:11 UTC, Gravewalker666 commented on src/main/java/org/sefglobal/scholarx/service/ProgramService.java
> +    public List<MentorResponse> getMentorResponses(long mentorId) throws ResourceNotFoundException {
Yeah, but it has a different signature.
Check the second part of the `get Mentor Response` in the [hive thread](https://sef.discourse.group/t/scholarx-model-update-to-improve-the-mentor-application/259/3?u=gravewalker)

2021-05-05 16:12 UTC, Gravewalker666 commented on src/main/java/org/sefglobal/scholarx/model/Question.java
> +    private String Question;
Good Catch, Thanks

2021-05-05 16:13 UTC, Gravewalker666 commented on src/main/java/org/sefglobal/scholarx/model/MentorResponse.java
> +public class MentorResponse implements Serializable {
Alright, I'll have a look

2021-05-06 03:13 UTC, Gravewalker666 commented on src/main/java/org/sefglobal/scholarx/model/MentorResponse.java
> +public class MentorResponse implements Serializable {
`BaseScholarxModel` got this generated `Id` column right? But we don't need a generated `Id` for this class ergo it's better to keep it this way right?

2021-05-06 05:15 UTC, Gravewalker666 commented on src/main/java/org/sefglobal/scholarx/model/Question.java
> +    private String Question;
Resolved with the commit 230b75e

2021-05-06 05:15 UTC, Gravewalker666 commented on src/main/java/org/sefglobal/scholarx/model/Question.java
> +public class Question {
Resolved with the commit 230b75e

2021-05-08 07:11 UTC, Piumal1999 commented on src/main/java/org/sefglobal/scholarx/model/MentorResponse.java
> +public class MentorResponse implements Serializable {
Ah right. Then it's okay.

2021-05-08 07:14 UTC, Piumal1999 approved these changes
Thank you @Gravewalker666 
Sorry for the delay

2021-05-09 10:41 UTC, merged