Add program state validation logic into mentee application functions
sef-global/scholarx pull request #290
Opened 2022-01-16 07:57 UTC by YaiyaSam

## Purpose

The purpose of this PR is to fix #288

## Goals

Validating program state before applying or updating the application as a mentee. 

## Approach

### Screenshots

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2022-01-16 08:15 UTC, Piumal1999 requested changes
Good job @YaiyaSam 

Could you please check the build? It is failing due to some tests. We'll have to update the tests related to these 2 methods. Also, update the method comments.

2022-01-16 08:37 UTC, YaiyaSam commented
> Good job @YaiyaSam
> 
> Could you please check the build? It is failing due to some tests. We'll have to update the tests related to these 2 methods. Also, update the method comments.

Yeah sure. Will do.

2022-01-18 14:31 UTC, Piumal1999 requested changes
Still 1 test is failing. Changing the program state in `updateMenteeData_withUnsuitableData_thenThrowBadRequest()` may fix the failing test.

2022-01-18 14:31 UTC, Piumal1999 commented on src/test/java/org/sefglobal/scholarx/service/MentorServiceTest.java
> +        mentor.setProfile(profile);
We don't need this part because we are not checking the profile id and mentor's profile

2022-01-18 14:31 UTC, Piumal1999 commented on src/test/java/org/sefglobal/scholarx/service/ProgramServiceTest.java
> +        program.setState(ProgramState.MENTEE_SELECTION);
```suggestion
        program.setState(ProgramState.MENTEE_APPLICATION);
```
This will fix the test

2022-01-18 15:13 UTC, YaiyaSam commented on src/test/java/org/sefglobal/scholarx/service/ProgramServiceTest.java
> +        program.setState(ProgramState.MENTEE_SELECTION);
I changed it. Thank you.

2022-01-18 18:49 UTC, Piumal1999 approved these changes
Good job! Thank you @YaiyaSam

2022-01-18 19:06 UTC, Gravewalker666 approved these changes

2022-01-18 19:06 UTC, merged