Updated the emails templates
sef-global/scholarx pull request #383
Opened 2023-05-03 07:09 UTC by chirandevinda

## Purpose

The purpose of this PR is to fix #382

## Goals
Update the emails templates

## Approach

have update the emails templates

### Screenshots

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2023-05-03 15:25 UTC, anjula-sack requested changes
@chirandevinda can you add the following line to the every email.

> To ensure that you receive our emails and they do not go to your spam folder, please add sustainableedufoundation@gmail.com to your email whitelist.

2023-05-04 01:14 UTC, chirandevinda commented
I will

On Wed, May 3, 2023 at 8:56 PM Anjula Shanaka ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> @chirandevinda <https://github.com/chirandevinda> can you add the
> following line to the every email.
>
> To ensure that you receive our emails and they do not go to your spam
> folder, please add ***@***.*** to your email
> whitelist.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sef-global/scholarx/pull/383#pullrequestreview-1411157521>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARRGLGSIMYRRL5PTLGPVRGLXEJ2IRANCNFSM6AAAAAAXT74AVY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-04 05:36 UTC, chirandevinda commented
> every email

means every email which going to send or just the ones that I edited?

2023-05-06 06:06 UTC, anjula-sack commented
> > every email
> 
> means every email which going to send or just the ones that I edited?

means every email which going to send @chirandevinda

2023-05-06 16:16 UTC, anjula-sack requested changes
I think we need the spaces I suggested @chirandevinda

2023-05-06 16:16 UTC, anjula-sack commented on src/main/java/org/sefglobal/scholarx/util/ProgramUtil.java
> +            "To ensure that you receive our emails and they do not go to your spam folder, please add sustainableedufoundation@gmail.com to your email whitelist.";
```suggestion
            " To ensure that you receive our emails and they do not go to your spam folder, please add sustainableedufoundation@gmail.com to your email whitelist.";
```

2023-05-06 16:16 UTC, anjula-sack commented on src/main/java/org/sefglobal/scholarx/util/ProgramUtil.java
> +                "for any clarifications." +
```suggestion
                "for any clarifications. " +
```

2023-05-06 16:16 UTC, anjula-sack commented on src/main/java/org/sefglobal/scholarx/util/ProgramUtil.java
> +            "Once again, congratulations on your selection! We cannot wait to have you on board." +
```suggestion
            "Once again, congratulations on your selection! We cannot wait to have you on board. " +
```

2023-05-06 16:16 UTC, anjula-sack commented on src/main/java/org/sefglobal/scholarx/util/ProgramUtil.java
> +                    "Please make the first contact with them as we have instructed them to wait for your email." +
```suggestion
                    "Please make the first contact with them as we have instructed them to wait for your email. " +
```

2023-05-06 16:16 UTC, anjula-sack commented on src/main/java/org/sefglobal/scholarx/util/ProgramUtil.java
> +                    "To ensure that you receive our emails and they do not go to your spam folder, please add sustainableedufoundation@gmail.com to your email whitelist.";
```suggestion
                    " To ensure that you receive our emails and they do not go to your spam folder, please add sustainableedufoundation@gmail.com to your email whitelist.";
```

2023-05-06 16:16 UTC, anjula-sack commented on src/main/java/org/sefglobal/scholarx/util/ProgramUtil.java
> +                    "for any clarifications." +
```suggestion
                    "for any clarifications. " +
```

2023-05-06 16:16 UTC, anjula-sack commented on src/main/java/org/sefglobal/scholarx/util/ProgramUtil.java
> +                        "To ensure that you receive our emails and they do not go to your spam folder, please add sustainableedufoundation@gmail.com to your email whitelist.";
```suggestion
                        " To ensure that you receive our emails and they do not go to your spam folder, please add sustainableedufoundation@gmail.com to your email whitelist.";
```

2023-05-06 16:16 UTC, anjula-sack commented on src/main/java/org/sefglobal/scholarx/util/ProgramUtil.java
> +                        "To ensure that you receive our emails and they do not go to your spam folder, please add sustainableedufoundation@gmail.com to your email whitelist.";
```suggestion
                        " To ensure that you receive our emails and they do not go to your spam folder, please add sustainableedufoundation@gmail.com to your email whitelist.";
```

2023-05-06 17:21 UTC, Piumal1999 commented on src/main/java/org/sefglobal/scholarx/util/ProgramUtil.java
> +                        "Once again, congratulations on your selection! We cannot wait to have you on board. We will keep you informed on the next steps, and in the meantime would like to invite you
```suggestion
                        "Once again, congratulations on your selection! We cannot wait to have you on board. We will keep you informed on the next steps, and in the meantime would like to invite you to go through some of the resources that would be useful to thrive as a great mentor in  " + program.get().getTitle() + ". <br /><br />" +
```

2023-05-09 12:29 UTC, Piumal1999 commented
Looks good to me. @anjula-sack shall we get this merged?

2023-05-09 12:37 UTC, anjula-sack approved these changes
Thank you! @chirandevinda

2023-05-09 12:37 UTC, merged